name: Terraform Deployment

on:
  push:
    branches:
      - main
# git clone / git checkout

# aws configure

# install terraform

# terraform init

# terraform plan

###################################################################################################################
# decalre the running agent
jobs:
 terraform:
   runs-on: ubuntu-latest

   steps:
##setup
   - name: Checkout repository
     uses: actions/checkout@v2
# install terraform
   - name: Set up Terraform
     uses: hashicorp/setup-terraform@v1
# aws configure
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1 # or hardcode us-east-1
##CI
  #  - name: Terraform Lint
  #    run: terraform fmt -recursive
# terraform init
   - name: Initialize Terraform
     run: terraform init

  #  - name: Terraform Validate
  #    run: terraform validate -no-color

##CD
# terraform plan
   - name: Terraform Plan
     run: terraform plan

  #  - name: Terraform Apply
  #    run: terraform apply --auto-approve
